DROP TABLE IF EXISTS TRANSACTIONS;
CREATE TABLE TRANSACTIONS
(
    TRANSACTION_ID VARCHAR(256) NOT NULL PRIMARY KEY,
    ACCOUNT_ID     VARCHAR(256) NOT NULL,
    AMOUNT         INT          NOT NULL,
);




